name: Create Release
on:
  push:
    branches:
      - main
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: ~1.24

      - name: Setup Golang caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-

      - uses: greatliontech/semrel@main
        id: semrel

      - name: Build
        if: steps.semrel.outputs.next-version != steps.semrel.outputs.current-version
        run: |
          mkdir -p dist
          go build -o dist/ocifs -ldflags "-X main.version=$APP_VERSION" ./cmd/ocifs
        env:
          APP_VERSION: ${{ steps.semrel.outputs.next-version }}

      - uses: actions/upload-artifact@v4
        if: steps.semrel.outputs.next-version != steps.semrel.outputs.current-version
        with:
          name: ocifs-${{ steps.semrel.outputs.next-version }}
          path: dist/ocifs

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.GLT_RELEASER_APP_ID }}
          private-key: ${{ secrets.GLT_RELEASER_APP_KEY }}

      - name: release
        run: semrel release
        env:
          SEMREL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEMREL_PROJECT: ${{ github.repository }}
